### ISSUE TITLE
Plugin not working correct in QGIS 3.22

### ISSUE THREAD

**Issue by NvBgm** [PedroVenancio/export_to_sql_server#1]
Afther update QGIS to v3.22 it gives me the following error

Uitvoeren van algoritme 1/1...
Algoritme Export to SQL Server (new connection) starten…
Parameters invoer:
{'ADDFIELDS': False,
'APPEND': False,
'A_SRS': <QgsCoordinateReferenceSystem: EPSG:4326>,
'CLIP': False,
'DATABASE': 'TIJDELIJK',
'DIM': 0,
'DRIVER': 'ODBC Driver 17 for SQL Server',
'FIELDS': [],
'GEOCOLUMN': 'ogr_geometry',
'GT': '',
'GTYPE': 2,
'INDEX': False,
'INPUT': 'D:/QGis/Shape_files/Collectieven/Collectieven-2021.shp',
'LAUNDER': False,
'MSSQLSPATIAL_USE_GEOMETRY_COLUMNS': True,
'OPTIONS': '',
'OVERWRITE': True,
'PASSWORD': 'xxxxxxx',
'PK': 'ogr_fid',
'PRECISION': True,
'PRIMARY_KEY': NULL,
'PROMOTETOMULTI': True,
'SCHEMA': '',
'SEGMENTIZE': '',
'SERVER': '84.129.166.26,2019',
'SHAPE_ENCODING': '',
'SIMPLIFY': '',
'SKIPFAILURES': False,
'SPAT': None,
'S_SRS': <QgsCoordinateReferenceSystem: EPSG:4326>,
'TABLE': 'dbo.collectieven',
'T_SRS': None,
'USER': 'xxxxx',
'WHERE': ''}

GDAL opdracht:
cmd.exe /C ogr2ogr.exe -progress -f MSSQLSpatial "MSSQL:server=84.129.166.26,2019; driver={ODBC Driver 17 for SQL Server}; database=TIJDELIJK; uid=xxxxxx; pwd=xxxxxxx;" -lco DIM=2 D:/QGis/Shape_files/Collectieven/Collectieven-2021.shp Collectieven-2021 -overwrite -nlt GEOMETRY -lco GEOMETRY_NAME=ogr_geometry -lco FID=ogr_fid -nln dbo.collectieven -s_srs EPSG:4326 -a_srs EPSG:4326 -nlt PROMOTE_TO_MULTI
GDAL uitvoer opdracht:
Proces werd onverwacht beëindigd
Algoritme Export to SQL Server (new connection) mislukt…
Execution failed after 2.34 seconds
Batch execution completed in 2.38 seconds
1 uitvoering mislukt. Bekijk het log voor meer details.

**Comment by PedroVenancio** [comment]
Thanks for reporting @NvBgm 

It is related to https://github.com/OSGeo/gdal/issues/4674

Will be fixed ASAP.

**Comment by NvBgm** [comment]
Thank you for the quick response

**Comment by PedroVenancio** [comment]
Fixed. New version (0.4) available from QGIS Python Plugins Repository.

**Comment by NvBgm** [comment]
Hi Pedro,
Great news. Updated and working like before ....
Thanks
