### ISSUE TITLE
Unable to find driver `MSSQLSpatial' since qgis update to 3.26

### ISSUE THREAD

**Issue by limmyjw** [PedroVenancio/export_to_sql_server#2]
GDAL opdracht:
cmd.exe /C ogr2ogr.exe -progress -f MSSQLSpatial "MSSQL:server=localhost; driver={ODBC Driver 17 for SQL Server}; uid=sa; pwd=Pinguin!0;" -lco DIM=2 D:/remote-sensing-master/R/DATA/BU08551802/2020/TUINEN/vector.gpkg buurt -lco GEOMETRY_NAME=geom -lco FID=id -nln buurt -t_srs EPSG:4326 -nlt PROMOTE_TO_MULTI --config MSSQLSPATIAL_USE_BCP NO
GDAL uitvoer opdracht:
ERROR 1: Unable to find driver `MSSQLSpatial'.
Proces gaf foutcode 1 terug
Execution completed in 0.53 seconds
Results:
{}

**Comment by PedroVenancio** [comment]
Hi @limmyjw 

Can you please check if you have `gdal-mss` and `msodbcsql` libs installed?

![imagem](https://user-images.githubusercontent.com/1331581/189126002-68463789-bb29-475a-97a4-8f9d00b39240.png)

**Comment by PedroVenancio** [comment]
Closing by lack of feedback. Reopen if needed.

**Comment by agiudiceandrea** [comment]
@PedroVenancio @jef-n please see the thread at https://www.mail-archive.com/qgis-user@lists.osgeo.org/msg51989.html. It seems the user reports that the issue occur in his system using QGIS 3.28.3 installed using the OSGeo4W all-in-one standalone installer .MSI, while it doesn't occur using QGIS 3.18.3 installed using the OSGeo4W all-in-one standalone installer .EXE.
Anyway, looking at is previous messages, it seems he initially reported to have installed 3.28.0, so I've asked to double check the actual non working version.

**Comment by PedroVenancio** [comment]
Hi @agiudiceandrea 
I've tested with both 3.28.3 standalone (.msi) and OSGeo4W and it seems to work as expected.
Can he check with 3.28.3?
Thanks!
