### ISSUE TITLE
Readme doesn't contain information, how to activate the plugin

### ISSUE THREAD

**Issue by quarkcz** [PedroVenancio/export_to_sql_server#3]
I've downloaded the plugin, installed, restarted QGIS, see the plugin in installed ones, but have no idea, where to find it in menu/how to activate the function.

Sure this is the information, that would be nice to read in readme :-)

**Comment by PedroVenancio** [comment]
Hi @quarkcz 

You will find the plugin in Processing Toolbox

![imagem](https://github.com/PedroVenancio/export_to_sql_server/assets/1331581/6125b0c4-9bd9-43b2-b44f-b424f516cc1f)

Reopen the ticket if needed.

Thanks!

**Comment by quarkcz** [comment]
Thank you, found it, used it, plugin works 🙏

Would you please add this information (how to activete the plugin) into readme file, because I'm sure, I'm not the only one, who would never find it there.
