### ISSUE TITLE
Na update naar de laatste versie van QGis werkt de plugin export_to_sql_server niet meer.

### ISSUE THREAD

**Issue by NvBgm** [PedroVenancio/export_to_sql_server#4]
Na update naar de laatste versie van QGis werkt de plugin export_to_sql_server niet meer.
I get the following python message.

2024-08-07T09:25:53     WARNING    Traceback (most recent call last):
              File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\ProcessingPlugin.py", line 428, in executeAlgorithm
              dlg = alg.createCustomParametersWidget(parent)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\algs\gdal\GdalAlgorithm.py", line 66, in createCustomParametersWidget
              return GdalAlgorithmDialog(self, parent=parent)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\algs\gdal\GdalAlgorithmDialog.py", line 57, in __init__
              self.mainWidget().parametersHaveChanged()
              File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\algs\gdal\GdalAlgorithmDialog.py", line 145, in parametersHaveChanged
              commands = self.algorithm().getConsoleCommands(parameters, context, feedback, executing=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/NvBgm/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\export_to_sql_server\OgrToSQLServer.py", line 233, in getConsoleCommands
              ogrLayer, layername = self.getOgrCompatibleSource(self.INPUT, parameters, context, feedback, executing)
              ^^^^^^^^^^^^^^^^^^^
             TypeError: cannot unpack non-iterable GdalConnectionDetails object
             

![image](https://github.com/user-attachments/assets/9815f0fc-8859-4388-80fb-4a7a27086697)

**Comment by PedroVenancio** [comment]
Hi @NvBgm 

What versions of QGIS and GDAL are you using? Can you past here the QGIS Help -> About content?

**Comment by NvBgm** [comment]
QGIS-versie
3.38.1-Grenoble
QGIS code revisie
3d4177af
Qt versie
5.15.13
Python versie
3.12.4
GDAL/OGR versie
3.9.1
PROJ versie
9.4.0
EPSG-register databaseversie
v11.004 (2024-02-24)
GEOS versie
3.12.2-CAPI-1.18.2
SQLite versie
3.45.1
PDAL versie
2.6.3
PostgreSQL client versie
unknown
SpatiaLite versie
5.1.0
QWT versie
6.2.0
QScintilla2 versie
2.14.1
OS versie
Windows 11 Version 2009




Actieve Python plug-ins
export_to_sql_server
0.4
layer2kmz
1.5.3
lizmap
4.3.20
plugin_exporter
0.2.1
plugin_reloader
0.10
ProjectPackager
0.7.2
qgis2web
3.22.0
SelectWithin
0.4
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

**Comment by PedroVenancio** [comment]
Thanks @NvBgm 

I've already fixed it and puled a new version (0.5) to QGIS plugins repository.

Let's wait for the approval. 

Thanks again!

**Comment by PedroVenancio** [comment]
The new version 0.5 is already available to upgrade from QGIS Plugins Manager.

**Comment by NvBgm** [comment]
Thanks for the quick response
It works like new again.
👍👍

⁣BlueMail voor Android downloaden ​

Op 8 aug 2024 10:41, om 10:41, Pedro Venancio ***@***.***> schreef:
